change: add clusterName label for identify each kubernetes cluster where K8UP is deployed
k8up-io/k8up pull request #1030
Opened 2024-12-09 13:57 UTC by lenglet-k

## Summary

We use K8up on multiple clusters. These multiple clusters perform backups of namespaces with the same name. All the metrics are sent in the same pushgateway. 

As the metrics have the same labels, we cannot have a detailed overview by cluster. This is the way K8UP currently works, which does not allow metric labels to be overloaded. This PR makes it possible to add a clusterName label per Kubernetes cluster. 

So in pushgateway we have backup metrics per Kubernetes cluster and per namespace, which improves monitoring of the execution of backups per Kubernetes cluster.

I essentially added a `clusterName` variable equivalent to the `promUrl` variable.

## Checklist

### For Code changes

- [ ] Categorize the PR by setting a good title and adding one of the labels:
  `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
  as they show up in the changelog
- [ ] PR contains the label `area:operator`
- [ ] Commits are [signed off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)
- [ ] Link this PR to related issues
- [ ] I have not made _any_ changes in the `charts/` directory.

2025-01-21 07:39 UTC, Kidswiss requested changes
Hi

Thanks for the contribution!

I found a typo, the rest looks good to me.

2025-01-21 07:39 UTC, Kidswiss commented on api/v1/check_types.go
> +	// ClusterName sets athe kubernetes cluster name to send to pushgateway for grouping metrics
```suggestion
	// ClusterName sets the kubernetes cluster name to send to pushgateway for grouping metrics
```

2025-01-23 08:07 UTC, Kidswiss commented
Hi @lenglet-k 

Looks like the linter doesn't like some new lines in the `check_types.go` file. Is it possible that your IDE or Editor doesn't use `LF` for new lines?

2025-02-28 08:22 UTC, lenglet-k commented
Hello,  what's the next ?

2025-02-28 08:38 UTC, Kidswiss commented
Hi @lenglet-k thanks for the ping.

Can you fix the [DCO check](https://github.com/k8up-io/k8up/pull/1030/checks?check_run_id=36110934507) so I can trigger all the other tests again?

2025-02-28 08:42 UTC, lenglet-k commented
> Hi @lenglet-k thanks for the ping.
> 
> Can you fix the [DCO check](https://github.com/k8up-io/k8up/pull/1030/checks?check_run_id=36110934507) so I can trigger all the other tests again?

It's done :)

2025-02-28 09:00 UTC, Kidswiss commented
@lenglet-k looks like some typo fixes didn't get into the rendered CRDs :(

a `make generate` should fix that.

2025-02-28 09:01 UTC, lenglet-k commented
Yes i check that now.

2025-02-28 11:47 UTC, Kidswiss approved these changes

2025-02-28 11:47 UTC, merged