Added service account annotations
k8up-io/k8up pull request #876
Opened 2023-07-31 12:12 UTC by mkotsalainen

## Summary

Helm chart service account annotation. Needed for EKS IRSA roles. I took code from:
https://github.com/external-secrets/external-secrets/blob/main/deploy/charts/external-secrets/values.yaml#L78
https://github.com/external-secrets/external-secrets/blob/main/deploy/charts/external-secrets/templates/serviceaccount.yaml#L12

2023-07-31 12:15 UTC, mkotsalainen commented
Here's related issue: https://github.com/k8up-io/k8up/issues/875

2023-08-02 06:37 UTC, Kidswiss requested changes
The comment for the parameter is wrong.

Could you please also run `make chart-docs` and `git rebase master --signoff` on your branch to make our checks pass.

2023-08-02 07:11 UTC, mkotsalainen commented
> The comment for the parameter is wrong.
> 
Good catch! Fixed.

> Could you please also run `make chart-docs` and `git rebase master --signoff` on your branch to make our checks pass.

Done.

2023-08-02 11:05 UTC, Kidswiss commented
hmmm... the DCO check is still not happy.

Can you try this way?
```
git rebase HEAD~6 --signoff
git push --force-with-lease origin sa-annotation
```

2023-08-02 11:28 UTC, mkotsalainen commented
> hmmm... the DCO check is still not happy.
> 
> Can you try this way?
> 
> ```
> git rebase HEAD~6 --signoff
> git push --force-with-lease origin sa-annotation
> ```

done

2023-08-03 10:46 UTC, mkotsalainen commented
is there something more I need to do on this?

2023-08-03 12:28 UTC, Kidswiss commented
Sorry I was off pretty early yesterday.

The commits look a bit weird now. Did you maybe rebase or squash before you executed my signoff command? It also signed commits from other people with your mail address.

Could you please drop those from the PR?

2023-08-03 16:30 UTC, mkotsalainen commented
If I'm not mistaken executed the commands in the order that they appeared in the chat. To tell you the truth I didn't really know what I was doing - I've never seen the  --force-with-lease flag before :)

Anyways, I've tried but I can't seem to get rid of those older commits from my branch.

If you want I can try to fork your repo again and redo from scratch, maybe that helps? Or you just take my diff and merge it - I don't care about attribution - I just want to be able give an AWS IRSA role to the k8up pod so that we can use it.

2023-08-04 06:33 UTC, Kidswiss commented
Yeah the whole DCO thing is a bit fiddly unfortunately... But it's required as we're a CNCF project.

I have a look to get this merged and released. Maybe I can cherry-pick your commits onto a new branch.

2023-08-04 06:56 UTC, Kidswiss commented
I've merged it via #877.

I just triggered a release, it should be available in a few minutes.

2023-08-04 06:56 UTC, closed without merging

2023-08-04 14:24 UTC, mkotsalainen commented
Thanks!!

2023-08-04 19:36 UTC, mkotsalainen commented
Sorry to bother you with this again but there is a whitespace in front of `annotations:`
<img width="1015" alt="2023-08-04 at 21 28" src="https://github.com/k8up-io/k8up/assets/180238/44fb1ffb-8aa3-4676-83c5-2e39dd5b78b0">
This causes the helm chart to render a non-valid ServiceAccount spec. Helm / yaml is picky.

This indentention level works:
```
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testing
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
```

<img width="1124" alt="2023-08-04 at 21 32" src="https://github.com/k8up-io/k8up/assets/180238/1c507b8f-8c3a-4d3e-95a1-c913fd6fcef7">

2023-08-07 06:57 UTC, Kidswiss commented
No worries, I should have caught that during the review 🙈. The git mess made me miss that, sorry. I'll create a fix for that.