fix: Add values to overwrite cleanup image
k8up-io/k8up pull request #890
Opened 2023-09-26 09:15 UTC by nheinemans-asml

## Summary

Adding new values to allow getting the cleanup image (bitnami/kubectl) from an internal registry.
Solves issue #889 

## Checklist

### For Helm Chart changes

- [ ] Categorize the PR by setting a good title and adding one of the labels:
  `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
  as they show up in the changelog
- [ ] PR contains the label `area:chart`
- [ ] PR contains the chart label, e.g. `chart:k8up`
- [X] Variables are documented in the values.yaml using the format required by [Helm-Docs](https://github.com/norwoodj/helm-docs#valuesyaml-metadata).
- [X] Chart Version bumped if immediate release after merging is planned
- [ ] I have run `make chart-docs`
- [ ] Link this PR to related code release or other issues.

2023-09-26 11:23 UTC, Kidswiss commented
Hi @nheinemans-asml 

Thanks for the contribution!

Can you please run `make chart-docs` and push that as well? That will genearte the docs for the new parameters.

Also the [DCO](https://github.com/k8up-io/k8up/pull/890/checks?check_run_id=17132883032) is required for the PR checks to pass.

2023-09-27 06:52 UTC, Kidswiss requested changes
Just one more thing, then it should be okay.

2023-09-27 06:52 UTC, Kidswiss commented on charts/k8up/values.yaml
> +  registry: hub.docker.com
```suggestion
  registry: docker.io
```

The registry URL is wrong.

2023-09-27 10:50 UTC, nheinemans-asml commented
> Just one more thing, then it should be okay.

Almost there, I forgot to run make chart-docs after my last change.

2023-09-27 11:05 UTC, Kidswiss commented
> > Just one more thing, then it should be okay.
> 
> Almost there, I forgot to run make chart-docs after my last change.

Yeah the readme still says `hub.docker.com` :)

2023-09-27 11:49 UTC, Kidswiss approved these changes
Cool!

Thanks for the contribution!

2023-09-27 11:50 UTC, merged