enhancement: Added oportuniy set ImagePullSecret
k8up-io/k8up pull request #923
Opened 2024-02-14 19:33 UTC by eunames

## Summary

Added oportuniy set ImagePullSecret param to manifest of job. It allows use a private registry for images when we use $BACKUP_IMAGE.

Fixes https://github.com/k8up-io/k8up/issues/567

## Checklist

### For Code changes

- [x] Categorize the PR by setting a good title and adding one of the labels:
  `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
  as they show up in the changelog
- [x] PR contains the label `area:operator`
- [x] Link this PR to related issues
- [ ] I have not made _any_ changes in the `charts/` directory.

### For Helm Chart changes

- [x] Categorize the PR by setting a good title and adding one of the labels:
  `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
  as they show up in the changelog
- [x] PR contains the label `area:chart`
- [x] PR contains the chart label, e.g. `chart:k8up`
- [x] Variables are documented in the values.yaml using the format required by [Helm-Docs](https://github.com/norwoodj/helm-docs#valuesyaml-metadata).
- [x] Chart Version bumped if immediate release after merging is planned
- [x] I have run `make chart-docs`
- [x] Link this PR to related code release or other issues.

2024-03-11 14:29 UTC, Kidswiss requested changes

2024-03-11 14:29 UTC, Kidswiss commented on charts/k8up/Chart.yaml
> +version: 4.4.4
I would actually see this as a feature, can you bump it to `4.5.0` please?

2024-05-28 11:50 UTC, TheBigLee commented
@eunames Could you rebase your branch so we can have a look at the change again and merge it if everything looks good?

2026-03-22 13:41 UTC, arska commented
Thanks for taking the time to contribute this! We really appreciate it.

Since there hasn't been any activity on this PR for about 2 years, we're going to close it for now to keep things tidy. If this is still relevant, feel free to reopen or submit a new PR — we'd be happy to review it.

2026-03-22 13:41 UTC, closed without merging